### ISSUE TITLE
goog.debug.freeze is not a function

### ISSUE THREAD

**Issue by olivergeorge** [vouch-opensource/krell#100]
For some reason `target/goog/debug/debug.js` doesn't seem to be loaded before `target/goog/events/browserevent.js` on android.  This leads to a "Failed to load file" error.

Test setup
* Krell master (35f7accd)
* Reagent tutorial but add an extra require in the awesome-project.core ns for `goog.events.BrowserEvent`

```
(ns awesome-project.core
  (:require [reagent.core :as r]
            [reagent.react-native :as rn]
            [goog.events.BrowserEvent]))   ; <--- Add this
```

Steps to repeat
* Start Krell repl
* npx react-native run-android

Expect: Clean boot

Actual: console error and logging by Krell indicating "Failed to load file"

```
07-17 08:23:20.138 31267 31457 E ReactNativeJS: TypeError: goog.debug.freeze is not a function. (In 'goog.debug.freeze([
07-17 08:23:20.138 31267 31457 E ReactNativeJS:   1,  // LEFT
07-17 08:23:20.138 31267 31457 E ReactNativeJS:   4,  // MIDDLE
07-17 08:23:20.138 31267 31457 E ReactNativeJS:   2   // RIGHT
07-17 08:23:20.138 31267 31457 E ReactNativeJS: ])', 'goog.debug.freeze' is undefined)
07-17 08:23:20.159 31267 31457 I ReactNativeJS: 'Failed to load file:', 'target/goog/events/browserevent.js'
```

Related experimentation
* I tried upgrading react-native-tcp-socket from 3.7.1 to 4.2.0 but the problem remains.
* Not immediately repeatable on iOS Simulator

**Comment by olivergeorge** [comment]
From minimal repo I get 

* Boots fine
* Boots fine
* Boots fine
* Boots fine

So not a great bug report yet.

**Comment by FSpoering** [comment]
I got to that stage when i was adding re-frame to the project. but i did not investigate it further.

**Comment by olivergeorge** [comment]
Failing consistently on Android simulator now so I'm hopeful I'll be able to find a simple repro (or fix a bug elsewhere).  

Seems like the app isn't requesting goog/goog/debug.js before trying to load target/goog/events/browser.js

**Comment by olivergeorge** [comment]
Yep, seems repeatable by simply requiring `goog.events.BrowserEvent`.

Updated description to match.

**Comment by olivergeorge** [comment]
So I think I fixed this but I'm not comfortable enough with the the associated code to claim victory.

I traced the code and found that the app was reaching CLOSURE_IMPORT_SCRIPT via loadFile for debug/debug.js but the server didn't seem to recieve the loadFile request.  (I could see the request before and after getting through).

I saw a likely looking IS_ANDROID in the js loadFile() function.  Hacking that out broke things but then upgrading react-native-tcp-socket to 4.2.0 fixed it.

So my working theory is
* that krell_repl.js had a workaround for an android bug in react-native-tcp-socket 3.7.1
* even with the workaround there are situations which lead to loadFile requests not getting through - it picks on debug/debug.js for some reason
* that bug has been fixed in 4.2.0

This seems the likely candidate: https://github.com/Rapsssito/react-native-tcp-socket/issues/54

I'm posting this before enough testing so treat it as a theory but here's my patch...

```
const loadFile = (socket, path) => {
    let req = {
            type: "load-file",
            value: path
        },
        payload = JSON.stringify(req)+"\0";
    socket.write(payload);
};
```

```
{:npm-deps {"@react-native-community/async-storage" "1.10.0"
            "react-native-tcp-socket"               "4.2.0"}}
```

There may be some related tidyup needed.

**Comment by olivergeorge** [comment]
I traced the code and found that the app was reaching CLOSURE_IMPORT_SCRIPT via loadFile for debug/debug.js but the server didn't seem to recieve the loadFile request.  I could see the request before and after getting through so I'm confident the logging was in place.

**Comment by olivergeorge** [comment]
I think perhaps `exists_` test is getting confused for the goog.debug case.

**Comment by olivergeorge** [comment]
In this example `target/goog/debug/error.js` is loaded first.  That's populating goog.debug with a Error and a few other keys.  I think the strategy used by `exists_` doesn't expect this.  As a result the exists_ testing for goog.debug is failing after that.

**Comment by swannodette** [comment]
Thanks for the detailed reproducer. Will take a look.

**Comment by olivergeorge** [comment]
Few questions which came out of discussing the issue...

Q: Should goog/debug/debug.js be loaded before target/goog/debug/errorcontext.js by convention since goog.debug.errorcontext is "under" goog.debug?

Neither android or iOS do this.  Based on that it could be the underlying issue is common to both (root bug) and `exists_` doesn't need to change.

Q: If the `exists_` test is necessary to avoid double loading namespaces then why doesn't iOS need an equivalent exists_ test?

My suspicion is that either `exists_` is needed for both (as second bug) or is unnecessary.

**Comment by bpringe** [comment]
I just ran into this as well after adding re-frame to my project. After making a code change and the app reloading, the error stopped being logged, and things seem to be working okay.
