### ISSUE TITLE
Cannot fix app crashes without reinstalling the app on the device

### ISSUE THREAD

**Issue by xafizoff** [vouch-opensource/krell#108]
How to reproduce:

1. Set wrong style property, e.g. `:alignItems "start"` (should be "flex-start")
2. App crashes
3. Fix the invalid property value
4. Open the app on the device
5. App crashes again
6. run `clj -m krell.main -co build.edn -c -r`
7. run `react-native run-android`
8. app is running w/o crashes (probably)

I dont know, it is related or not, but often app hangs on screen `Waiting for Krell to load files.`. Nothing happens, unless I do 6 and 7.

My Krell version is `44b36571e401c730ca3b1ae7abf1e044687414e5`

PS I've tried to clear the app cache on the android. Now there's no crash but it's stuck "waiting for krell to load files". And the  REPL also does not respond. 

The best way I have found so far is to clear app's storage, and restart the REPL.

**Comment by swannodette** [comment]
Pretty sure this is resolved w/ master which is a fairly large refactor of how Krell works. If you can still reproduce, re-open.
