### ISSUE TITLE
Redirect the using Calva info to the Calva docs site

### ISSUE THREAD

**Issue by PEZ** [vouch-opensource/krell#132]
Hello,

I think part of what got confusing with issue #113 is that the information about how to use Calva really belongs on the Calva side of things. So I have added a page to calva.io about using it with Krell;

https://calva.io/krell/

Can you update the wiki, and replace the usage with Calva info there with a reference to this new page, @swannodette ?

**Comment by swannodette** [comment]
@pez done!
