### ISSUE TITLE
Error jacking in from CIDER/Calva using master version 

### ISSUE THREAD

**Issue by laynor** [vouch-opensource/krell#136]
I can run the app correcly, and can open a working cljs repl  issuing
```
clj -M -m krell.main -co build.edn -r
```
at the command line.
However, when I try to start the repl from cider or calva, I get this error
```
   ReferenceError: Can't find variable: cljs
```
full stack trace here: https://gist.github.com/laynor/4944b74a36691b8c3be7bb852818fe87

The full project repo is here https://github.com/laynor/krelltest
I asked for help on clojurians, and the project appears to work on other machines. However, I verified with a colleague that's using the same system I'm using and reproduced the issue on his machine.
As a result of this issue, the cider repl is stuck at the user => prompt (clojure/java repl if I understand correctly) and never reaches the cljs.user => repl.

Here are my system details:
Os: Arch linux
Emacs: recent version compiled from sources (master). native comp enabled
Cider version: "CIDER 1.1.0 (package: 20210422.802) (Plovdiv)"
clojure --version: Clojure CLI version 1.10.3.822

java version: tried both openjdk version "1.8.0_292"and jdk 8 downloaded from the Oracle homepage.

Node version 14.3.0

This krell version is working for me:  d0e115309580ca0bdc782e4ca396df66a357d212.

I still haven't investigated what commit exactly introduces the issue.

**Comment by swannodette** [comment]
I believe this was a documentation issue only.
