### ISSUE TITLE
Building and starting REPL in a single command

### ISSUE THREAD

**Issue by adaitche** [vouch-opensource/krell#138]
The README and the Reagent Tutorial in the Wiki say that one can build the project and start the REPL in a single command:
```
clj -M -m krell.main -co build.edn -c -r
```

This doesn't work for me. For example, if I delete `index.js` and execute the command above, it is not recreated. Executing the command just with `-c` works though.

My `clj` version is `1.10.3.855` and here is my `deps.edn` (taken from the tutorial):
```
{:deps {io.vouch/krell {:git/url "https://github.com/vouch-opensource/krell.git"
                        :sha "a6bf860df2385384b36dea68bcf2e3163a14bfa8"}
        io.vouch/reagent-react-native {:git/url "https://github.com/vouch-opensource/reagent-react-native.git"
                                       :sha "0fe1c600c9b81180f76b94ef6004c2f85e7d4aa0"}
        reagent/reagent {:mvn/version "0.10.0"
                         :exclusions [cljsjs/react cljsjs/react-dom]}}}
```

**Comment by gerdint** [comment]
I had this issue too.

**Comment by mattdamon108** [comment]
I have this issue too. When I first follow the tutorial in wiki, I couldn't figure out what was wrong. Finally I could ran my app successfully after running commands in this order and seperately.
```shell
clj -M -m cljs.main -co "{:deps-cmd \"yarn\"}" --install-deps
clj -M -m krell.main -co build.edn -c
clj -M -m krell.main -co build.edn -r
```

**Comment by swannodette** [comment]
It was broken, fixed in master.
