### ISSUE TITLE
Extending Krell For Use with Expo

### ISSUE THREAD

**Issue by bnert** [vouch-opensource/krell#147]
In the README, the project mentions that Krell can be extended for integrating with Expo. I have been attempting to do so and am running into issues, mainly around the app root never being registered.

Do you have an example of how to provide your own `index.js` file for integrating with other tools?

Let me know if you need more context (code snippet, error messages, etc...), and I can provide them.

Thanks in advance, and thanks for the cool utility 🙂

**Comment by hkjels** [comment]
I'm also wondering about this. I'm not so much interested in `Expo`, but I'm interested in running `Krell` with `React-native-web`. I think I've made some progress; at least on bundling with `Metro`, but I'm still not familiar enough with the inner workings of `Krell` to see how far I am from a working solution.

To your issue specifically @bnert , have you tried something like:
```js
// Whereas 'app' is the root-node of your html-template
AppRegistry.runApplication(appName, {rootTag: document.getElementById('app')});
```
at the bottom of your `krell_index.js` file?

**Comment by bnert** [comment]
@hkjels thanks for the suggestion.

I am still running into issues, mainly around the web build. The error has to do with the `process` global variable not existing on the web, due to some of the associated [krell compat/repl](https://github.com/vouch-opensource/krell/blob/ed372b4dc4c8b74219ac0f7d89fa6568270144dd/resources/krell_repl.js#L181) code requiring access toe the `process` variable.

**Comment by hkjels** [comment]
I'm going to look more into how all this works. Doing a production-build works fine, so it's just the REPL-connection stuff that does not pan out for obvious reasons.

**Comment by bnert** [comment]
I'm going to close this out, given krell isn't focused on web.
