### ISSUE TITLE
react-native-tcp-socket incopatibility when using the react native template

### ISSUE THREAD

**Issue by benjamin-asdf** [vouch-opensource/krell#148]
steps: 

https://github.com/vouch-opensource/krell/wiki/Reagent-Tutorial

when you do 
```npx react-native run-android```

there is a compile error in module `:react-native-tcp-socket` "plugin maven doesn't exist" or some such. 

issue: 

recent "AwesomeProject" uses gradle 7
react-native-tcp-socket version "5.2.0" uses maven plugin which got removed.

Temp fix (to be able to keep going)
`yarn add react-native-tcp-socket`
to install the latest version which does not use the broken plugin. 

proposed solution: 

change deps.cljs to 

```clojure
{:npm-deps {"react-native-tcp-socket" "5.6.0"
            "react-native-device-info" "8.1.2"}}
```
(bump the version)

**Comment by guillempuche** [comment]
@swannodette, could you deploy @benjamin-asdf 's suggestion?

**Comment by swannodette** [comment]
I just released 0.5.4 with this change, please give let a try and close this issue if it works for you.

**Comment by guillempuche** [comment]
@swannodette, works fine now! Thanks for your quickness.

**Comment by swannodette** [comment]
👍
