### ISSUE TITLE
Support preloads compiler option

### ISSUE THREAD

**Issue by olivergeorge** [vouch-opensource/krell#54]
I think `:preloads` aren't being picked up.

My use case is installing binaryage/cljs-devtools via the preloads complier option.

Also tried a simple console statement in a preload namespace but it doesn't appear in the react native debugger (chrome terminal).

**Comment by swannodette** [comment]
hrm, `:preloads` should work fine - I'll try to make a minimal case and confirm

**Comment by swannodette** [comment]
@olivergeorge one thing I'm curious about is whether the preloads you're trying use appears in your `:ouput-dir` as compiled files?

**Comment by olivergeorge** [comment]
I can see the files in the target directory but the preload namespace never says hello.

```
AwesomeProject % cat src/awesome_project/preload.cljs 
(ns awesome-project.preload)

(js/console.log (pr-str ::hello))

AwesomeProject % cat build.edn 
{:main awesome-project.core
 :output-to "target/main.js"
 :output-dir "target"
 :preloads [awesome-project.preload]}

AwesomeProject % find target/awesome_project 
target/awesome_project
target/awesome_project/preload.js.map
target/awesome_project/preload.js
target/awesome_project/preload.cljs
target/awesome_project/core.js
target/awesome_project/core.js.map
target/awesome_project/core.cljs.cache.json
target/awesome_project/preload.cljs.cache.json
target/awesome_project/core.cljs
```

**Comment by swannodette** [comment]
Was able to reproduce. Yeah in dev mode we need to load preloads.
