### ISSUE TITLE
Cursive IDE Example

### ISSUE THREAD

**Issue by staypufd** [vouch-opensource/krell#83]
It would be nice to see how Cursive and figwheel would work with this.

**Comment by olivergeorge** [comment]
Here's an example of how I have Cursive setup:

![image](https://user-images.githubusercontent.com/99447/81395164-8149a380-9166-11ea-8f07-9920f9efb0b5.png)

No need for Figwheel.  Krell provides the compile, repl & code reloading experience.

**Comment by swannodette** [comment]
Added to the wiki, will update README to link.
