### ISSUE TITLE
Bootstrap non-repl dev build by fetching assets through metro bundler 

### ISSUE THREAD

**Issue by olivergeorge** [vouch-opensource/krell#88]
The Metro bundler can serve up static files.

This might provide a mechanism to allow the compile (e.g. -c, not -c -r) to bootstrap itself by using the bundler to serve up JS files.

For example, this URL returns the a source file in the target directory:
http://localhost:8081/target/npm_deps.js

As an aside, the same approach might be leveraged to take a responsibility off the REPL.

**Comment by swannodette** [comment]
A nice idea, will look into it

**Comment by swannodette** [comment]
Was fixed with #125
