### ISSUE TITLE
High CPU load

### ISSUE THREAD

**Issue by Looveh** [vouch-opensource/krell#93]
I love the promise of krell and wish to test using it both for my daily work using cljs+RN as well as for hobby projects. I started out by copying the reagent example found in the wiki and start compilation with:

```bash
clj -m krell.main -co build.edn -c -r
```

The java process that starts quickly goes up to idling at 100% CPU on my machine and continues on that level, both before and after the simulator connects.

I'm running an 2019 15 inch MacBook, 8-Core i9 with 16G RAM, so 100% CPU with fans running on max seems a bit extreme to me.

```clojure
; deps.edn

{:deps {io.vouch/krell {:git/url "https://github.com/vouch-opensource/krell.git"
                        :sha "ab503aade8447b794454055f12e8935787f8ac08"}
        io.vouch/reagent-react-native {:git/url "https://github.com/vouch-opensource/reagent-react-native.git"
                                       :sha "54bf52788ab051920ed7641f386177374419e847"}
        org.clojure/clojurescript {:git/url "https://github.com/clojure/clojurescript.git"
                                   :sha "00079768f9104b17f4130cd710a2f636e046cb07"}
        reagent {:mvn/version "0.10.0"
                 :exclusions [cljsjs/react cljsjs/react-dom]}}}
```

I'd love to dig deeper and understand what's causing the high CPU load on my machine but I'm lost at where to start to look. Any suggestions?

**Comment by solidfox** [comment]
Just had the same problem. Seems to be fixed in the latest commit so change the :sha for your krell dep to `5080e776f256ee497874c2bbe680a5280c1a2921`. 💡

**Comment by Looveh** [comment]
@solidfox Thanks, that solved it :+1: for me
