### ISSUE TITLE
Fast refresh does not re-render changed components unless main is changed

### ISSUE THREAD

**Issue by solidfox** [vouch-opensource/krell#95]
Hi! 

Thanks for your fantastic efforts with Krell! I am happily using krell with a rather large project that previously used re-natal and figwheel. 

I have run into the problem that react does not re-render changed components unless the file containing -main is changed.

Is this a limitation in Krell or Fast Refresh and is there something we could do about it? I imagine that in the worst case one could just keep adding and removing a linebreak to the end of the main file but I hope there's a less hacky way.

**Comment by swannodette** [comment]
Again this ticket is old. Try master and feel free re-report.
