### ISSUE TITLE
Reagent Tutorial is out of date vs Master & Readme details

### ISSUE THREAD

**Issue by olivergeorge** [vouch-opensource/krell#96]
I think the tutorial needs a few tweaks to avoid confusing people.

If the SHA was updated to the current latest master commit then...

Android permission bit can be removed...
https://github.com/vouch-opensource/krell/commit/a21b763b2f48093f5dd85cec8fcfa6c465aa98ad#diff-04c6e90faac2675aa89e2176d2eec7d8

I think there are a few known gotchas with the version referred to in the tutorial but I can't recall details.  

Master seems stable.

**Comment by swannodette** [comment]
Fixed
