### ISSUE TITLE
Row too big to fit into CursorWindow

### ISSUE THREAD

**Issue by olivergeorge** [vouch-opensource/krell#97]
We hit this error when AsyncStorage.getItem was trying to retrieve a 2.5mb js file on Android.

We broke up the file into a few separate namespaces but that didn't fix it.  Once we cleared the user data off the simulator and started fresh it was fine.

I think a try/catch around the AsyncStorage.getItem call might be a good way to avoid this being fatal and hard to recover from.

Note: cljs/core.js is 1.3mb on our build.  That's getting close to 2mb.  Not sure if there are compiler options which would affect code size generated signficantly but if there are then this might be a hard limit which krell needs to consider.

**Comment by swannodette** [comment]
To add more detail to this issue - the exception is coming from SQLite, this has of course been encountered elsewhere in RN projects - https://stackoverflow.com/questions/57014171/react-native-asyncstorage-row-too-big-to-fit-into-cursorwindow
