### ISSUE TITLE
Repl doesn't initialise app correctly on second install

### ISSUE THREAD

**Issue by olivergeorge** [vouch-opensource/krell#99]
For some recent testing I needed to see the app boot to a pristine environment.  To do this I had to restart the krell repl which I suspect was necessary only as a workaround for an underlying bug.

Setup:
* Start metro bundler with `npx react-native start`

Each iteration
* Uninstall the app with `adb uninstall com.awesomeproject`
* Stop krell repl
* Start krell repl with `clj -m krell.main -co build.edn -c -r` 
* Run on android with `npx react-native run-android`

I don't think it should have been necessary to restart the krell repl each time but it was.  Without this step the app was "waiting for krell" indefinitely.

This is repeatable using an android emulator.  Also happens for iOS Simulator.

**Comment by swannodette** [comment]
This ticket needs more info. I'm assuming again this is not reproducible on an emulator, only on the Android device you actually have yes?

**Comment by olivergeorge** [comment]
I'm able to repeat without a physical device.  Updated description.

**Comment by swannodette** [comment]
I just tried deleting an existing Awesome Project and going through the above steps, I could not repro on iOS.

**Comment by olivergeorge** [comment]
I’ll test again

**Comment by swannodette** [comment]
Another resolved by master. The REPL is longer involved w/ file loading, and many corrupted states are no longer possible.
